# Generated by Django 2.0.7 on 2018-07-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourpaymentorm',
            name='end_rout_date',
        ),
        migrations.RemoveField(
            model_name='hourpaymentorm',
            name='start_rout_date',
        ),
    ]
