# Generated by Django 2.0.7 on 2018-07-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180714_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkDayORM',
            new_name='WorkedDayORM',
        ),
    ]
