export const projectActionTypes = {
    GET: "GET_PROJECT",
    GET_ALL: "GET_ALL_PROJECTS",
    GET_ALL_SUCCESS: "GET_ALL_PROJECTS_SUCCESS",
    GET_ALL_FAILURE: "GET_ALL_PROJECTS_FAILURE",
    CLEAR_ALL: "CLEAR_ALL_PROJECTS",
    REMOVE: "REMOVE_PROJECT",
    CREATE: "CREATE_PROJECT",
    UPDATE: "UPDATE_PROJECT",
    GET_TOTAL: "GET_TOTAL"
}
