# Generated by Django 2.0.6 on 2018-07-12 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('start_rout_date', models.DateTimeField(default=datetime.datetime(2018, 7, 12, 10, 12, 27, 420701, tzinfo=utc))),
                ('end_rout_date', models.DateTimeField(default=datetime.datetime(2018, 8, 11, 10, 12, 27, 421202, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='MonthPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 7, 12, 10, 12, 27, 419698, tzinfo=utc), null=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2018, 8, 11, 10, 12, 27, 419698, tzinfo=utc), null=True)),
                ('type_of_payment', models.CharField(choices=[('H_P', 'Часовой'), ('M_P', 'По месяцом'), ('T_P', 'По задачам')], max_length=4)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=None, to='account.UserORM')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TaskPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('cost', models.FloatField(default=0)),
                ('status', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=None, to='project.ProjectModel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date(2018, 7, 12))),
                ('have_worked', models.BooleanField(default=False)),
                ('month_payment', models.ForeignKey(on_delete=None, to='project.MonthPayment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.DateTimeField(default=datetime.datetime(2018, 7, 12, 10, 12, 27, 421703, tzinfo=utc))),
                ('end_work', models.DateTimeField(default=datetime.datetime(2018, 8, 11, 10, 12, 27, 421703, tzinfo=utc))),
                ('rate', models.ForeignKey(on_delete=None, to='project.HourPaymentModel')),
            ],
        ),
        migrations.AddField(
            model_name='monthpayment',
            name='project',
            field=models.ForeignKey(on_delete=None, to='project.ProjectModel'),
        ),
        migrations.AddField(
            model_name='hourpaymentmodel',
            name='project',
            field=models.ForeignKey(on_delete=None, to='project.ProjectModel'),
        ),
    ]
