export const projectActionTypes = {
    GET: "GET_PROJECT",
    ADD_ALL: "ADD_ALL_PROJECTS",
    CLEAR_ALL: "CLEAR_ALL_PROJECTS",
    REMOVE: "REMOVE_PROJECT",
    CREATE: "CREATE_PROJECT",
    UPDATE: "UPDATE_PROJECT",
    GET_TOTAL: "GET_TOTAL"
}
