export const ProjectConstant = {
    GET_PROJECT: "GET_PROJECT",
    ADD_ALL_PROJECTS: "ADD_ALL_PROJECTS",
    CLEAR_ALL_PROJECTS: "CLEAR_ALL_PROJECTS",
    DELETE_PROJECT: "DELETE_PROJECT",
    CREATE_PROJECT: "CREATE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    GET_TOTAL: "GET_TOTAL"
}
